spring:
  datasource:
    url: jdbc:h2:mem:anagraficadb
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

app:
#  upload:
#    path: /home/ubuntu/CODEGEN/Reax4Java/java-sources/
  api:
    prefix: /api/java