spring.application.name=usermanagement
logging.level.org.springframework.security.web=DEBUG
logging.level.org.springframework.security.authentication=DEBUG


# Porta del server
#server.address:0.0.0.0
#server.port=8081
server.port=${PORT:8081}
server.address=0.0.0.0

spring.security.user.name = user
spring.security.user.password = 1234
